FROM @@DOCKIMG@@

# Install basic tools
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get --yes update
RUN apt-get --yes install sudo util-linux make @@DEBSRCDEPS@@
RUN apt-get --yes clean
RUN addgroup htchain
RUN umask 0337 && \
    echo '%htchain ALL=(ALL:ALL) NOPASSWD: /usr/bin/apt, /usr/bin/apt-get' \
    > /etc/sudoers.d/htchain
