FROM @@DOCKIMG@@

USER root

# Install basic tools
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get --yes update
RUN apt-get --yes install sudo util-linux make locales @@DEBSRCDEPS@@
RUN apt-get --yes clean
RUN echo 'en_US.UTF-8 UTF-8' > /etc/locale.gen && locale-gen
RUN addgroup htchain
RUN umask 0337 && \
    echo '%htchain ALL=(ALL:ALL) NOPASSWD: /usr/bin/apt, /usr/bin/apt-get' \
    > /etc/sudoers.d/htchain
